package com.lezhin.api.search.model;

import lombok.Data;

@Data
public class Product {
    public String delivery_smart_pick_yn;
    public String spd_delivery_crosspick_yn;
    public String spd_id_list;
    public String benefit_4th_price;
    public String spd_delivery_process_type_code;
    public String itm_regist_date;
    public String send_close_time;
    public String pd_mapp_yn;
    public String spd_regist_date;
    public String spd_sale_type_code;
    public String delivery_cost;
    public String benefit_spd_free_gift_wrap_yn;
    public String itm_name;
    public String spd_delivery_cost_no;
    public String toys_pd_yn;
    public String itm_id;
    public String delivery_premium_yn;
    public String imp_dvs_cd;
    public String std_ut_cd;
    public String pd_id;
    public String sitm_name;
    public String sitm_id;
    public String benefit_3rd_price;
    public String spd_id;
    public String spd_standard_category_id;
    public String sitm_base_price;
    public String mall;
    public String benefit_1st_price;
    public String pd_regist_date;
    public String auto_term_text;
    public String etv_pd_yn;
    public String econ_object_id;
    public String sitm_image_url;
    public String crd_prd_dc_fl_val;
    public String pd_name;
    public String spd_hope_day_yn;
    public String editdate;
    public String delivery_overseas_yn;
    public String premium_pd_yn;
    public String spd_delivery_reservation_type_code;
    public String key_element;
    public String crd_prd_dc_amt;
    public String pd_sale_status_code;
    public String delivery_today_yn;
    public String spd_name;
    public String spd_sale_start_datetime;
    public String spic_euse_pd_yn;
    public String benefit_2nd_price;
    public String sitm_capacity;
    public String delivery_due_date;
    public String sat_send_close_time;
    public String thdy_pd_yn;
    public String delivery_quick_yn;
    public String sat_send_possible_yn;
    public String pd_standard_category_id;
    public String sitm_tr_no;
    public String pd_typ_cd;
    public String pd_model_code;
    public String crd_prd_dc_fx_val;
    public String spd_delivery_method_code;
    public String sitm_group_cp_code;
    public String spd_delivery_pd_type_code;
    public String spd_regular_delivery_yn;
    public String spd_sale_end_datetime;
    public String std_capa;
    public String sckwd_concat;
    public String itm_sale_status_code;
    public String arv_dt_key;
    public String regdate;
    public String pd_age_limit_code;
    public String user_score_point;
    public String pd_review_count;
    public String lrtr_no;

    //sas Inject field
    private Injected injected;
}
