version: "3.7"

services:

#  database:
#    container_name: postgres
#    image: postgres:latest
#    restart: always
#    ports:
#      - 5432:5432
#    environment:
#      POSTGRES_DB: board_db
#      POSTGRES_USER: board
#      POSTGRES_PASSWORD: board
#    volumes:
#      - /Users/labtop/intellij/docker-postgres/:/var/lib/postgresql/data

  cache:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - /Users/jongok/Documents/App/docker-redis/:/data

  application:
    container_name: lezhin_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:9201
   # environment:
      #SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/board_db
      #SPRING_DATASOURCE_USERNAME: board
      #SPRING_DATASOURCE_PASSWORD: board
    depends_on:
      #- database
      - cache


# 외부에서 도커 컨테이너로 접근 하기 위한 커맨드
#docker exec -it postgres bash
#psql -U <POSTGRES_USER> -d <POSTGRES_DB>
#docker exec -it redis redis-cli