server:
  port : 9201

spring:
  datasource:
    url: jdbc:mariadb://soulchild-mariadb.c76q0uqkytst.ap-northeast-2.rds.amazonaws.com:3306/soulchild_content??characterEncoding=UTF-8&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: 8824guss!
    driverClassName: org.mariadb.jdbc.Driver
    hikari:
      connectionTimeout: 3000
      maximumPoolSize: 10
      poolName: HikariCP
      readOnly: false
      connectionTestQuery: SELECT 1
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        trace: false
#        web-allow-others: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  cloud:
    openfeign:
      client:
        config:
          default:
            loggerLevel: full
            connect-timeout: 5000
      category:
        url: https://srch-capi.lotteon.com/search/render/render.ecn?render=nqapi&platform=m&collection_id=6&u9=json&u10=1&mallId=1
      display:
        url: https://pbf.lotteon.com/csearch/v1/navigate/category/product
#
#
#logging:
#  level:
#    study: TRACE
#    org.hibernate:
#      type:
#        descriptor.sql: trace